### ISSUE TITLE
Footer Background (Web Issue)

### ISSUE THREAD

**Issue by marisabivi** [marisabivi/g-conservancy#10]
Doesn't cover all the content in web browser. Both Chrome and safari

<img width="1132" alt="screen shot 2016-02-27 at 3 02 12 pm" src="https://cloud.githubusercontent.com/assets/6371052/13375020/219994a6-dd63-11e5-82df-c12bc41936a5.png">

@shelbyboyd

**Comment by shelbyboyd** [comment]
yeah, someone deleted the address, so now it doesnt push the footer down. i still have .address in my css but its gone in the html. sorry who ever deleted it, but its going back in.
