### ISSUE TITLE
Header (Android)

### ISSUE THREAD

**Issue by marisabivi** [marisabivi/g-conservancy#11]
Can't click on hamburger when viewing on Android, or it will stay open.

![12788335_10205403786926725_2009802861_o](https://cloud.githubusercontent.com/assets/6371052/13375074/6930acfe-dd64-11e5-9f60-72cd1f187d0d.jpg)
![12789973_10205403786806722_208174173_o](https://cloud.githubusercontent.com/assets/6371052/13375076/6af37800-dd64-11e5-9af5-61035ef97793.jpg)

@malo0140

**Comment by malo0140** [comment]
This is the fantastic error.
