### ISSUE TITLE
Index HTML Validation

### ISSUE THREAD

**Issue by marisabivi** [marisabivi/g-conservancy#111]
The element _button_ must not appear as a descendant of the _a_ element.

**Comment by marisabivi** [comment]
Also will need the role="button" added afterwards.

**Comment by marisabivi** [comment]
Your overlays and text id's on index are giving a lot of warnings and errors in the validator.

<img width="567" alt="screen shot 2016-03-14 at 12 39 26 am" src="https://cloud.githubusercontent.com/assets/6371052/13735219/479a175e-e97d-11e5-91d0-96fe3e509b8c.png">
<img width="576" alt="screen shot 2016-03-14 at 12 41 56 am" src="https://cloud.githubusercontent.com/assets/6371052/13735259/a5473026-e97d-11e5-9155-b659e5ac8200.png">

**Comment by malo0140** [comment]
if i change that nothing works.
