### ISSUE TITLE
Role="Role"

### ISSUE THREAD

**Issue by marisabivi** [marisabivi/g-conservancy#112]
Supposedly, this code is somewhere in our site. Issue being, role="role" rather than button but I can't find it anywhere....
`<a role="role" href="/galapagos-conservancy/donate/"><button class="idonate-btn">Donate</button></a>
`
@isabelle6 @malo0140 @saracase @shelbyboyd

**Comment by marisabivi** [comment]
Some other things that have shown up as problems in html validation that I haven't been able to find are an open `<main>` element, an unclosed `<main>` element and a stray `<main>` element as well as to stray `</div>`. Please check out your code but I'm doubting the validator... 

<img width="999" alt="screen shot 2016-03-14 at 7 50 13 am" src="https://cloud.githubusercontent.com/assets/6371052/13743655/71e7130e-e9b9-11e5-8075-d3d7c752d7fb.png">

**Comment by malo0140** [comment]
divs fixed are fixed as well as the role. The main element is showing up because i have it in the default layout.
