### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by marisabivi** [marisabivi/g-conservancy#12]
Logo needs the organization name added.

@saracase @isabelle6

**Comment by malo0140** [comment]
I don't think the logo needs the name in it.

**Comment by shelbyboyd** [comment]
i think it does so people actually know what site their on and what the name of the company is

**Comment by marisabivi** [comment]
The company isn't well known enough that just having an icon will get them by. There are other conservancies that make use of a turtle in their logo too so it'd be best for us to identify our conservancy along with our turtle.

**Comment by isabelle6** [comment]
I agree, it makes sense to have the name. We'll get on that.

**Comment by isabelle6** [comment]
I added the logo to the img folder.
