### ISSUE TITLE
Images error 

### ISSUE THREAD

**Issue by malo0140** [marisabivi/g-conservancy#16]
<img width="617" alt="screen shot 2016-03-01 at 12 08 57 pm" src="https://cloud.githubusercontent.com/assets/6340286/13437502/95d59238-dfb2-11e5-94b1-340d185d09dd.png">

I keep getting this Prepros error with the images. Any way to fix this?

@saracase @isabelle6 @shelbyboyd @marisabivi

**Comment by ghost** [comment]
This error comes up because we saved for web all the images so they were already optimized in photoshop, so prepros can't optimize it again, no way to fix this
