### ISSUE TITLE
iconic font

### ISSUE THREAD

**Issue by malo0140** [marisabivi/g-conservancy#29]
iconic font doesn't show up in android.

**Comment by malo0140** [comment]
add css file for https://file.myfontastic.com/i49qVkvyeHfQECBiRoLBTB/icons.css. 
instructions on http://stackoverflow.com/questions/33554728/fontastic-me-not-working-on-mobile

**Comment by marisabivi** [comment]
Attempting to fix this. I've added the css but the code to replace is actually part of another link and is not in the css to added. The best i've gotten is letters to replace the icons in chrome but not opera. Icons are now clickable in default browser on my G3. 

![12822676_10205455447218200_838053734_o](https://cloud.githubusercontent.com/assets/6371052/13559970/d3f54656-e3e7-11e5-9a8c-6f7f4695540f.jpg)

**Comment by malo0140** [comment]
The icons show up now in shelby's browser.

**Comment by marisabivi** [comment]
Still not showing for me but okay
