### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by marisabivi** [marisabivi/g-conservancy#3]
I'd say we need a photo of the Galapagos from above? Map and actual shots?

@isabelle6 @saracase 

(Other needed photos can be commented here @malo0140, @shelbyboyd)

**Comment by ghost** [comment]
Added more

**Comment by malo0140** [comment]
We need photos for the news articles.

**Comment by marisabivi** [comment]
Photos used on the index carousel need to be found at a larger size, about 1024px width.

**Comment by malo0140** [comment]
I'm going to resize the images I am using in the carousel. Ill re-name/ save a different copy so they don't change anywhere else on the site.
