### ISSUE TITLE
Font Sizing

### ISSUE THREAD

**Issue by malo0140** [marisabivi/g-conservancy#43]
Everyone is using different font size on every page. Please go back into your scss and delete all the font-sizing. It should pick up the style from the type.css. Any buttons used should have the @import button;
@marisabivi @saracase @isabelle6 @shelbyboyd

**Comment by marisabivi** [comment]
Title related to the page should be in a  `<h2>` ex. about, news etc
Sub headings `<h3>` with a class of .exa. 
<strike>We have too many`<h1>`s. We can only have one and it will be on the index! Using the class of .exa will get you the font size of a `<h1>` should you feel you need it.</strike>

Please change this on the pages you are working on and if there is anything you are unsure of ask!  Exceptions for sign up and donate page, for the subheadings. 

@malo0140 @shelbyboyd @isabelle6 @saracase

**Comment by malo0140** [comment]
Every page needs an h1.

**Comment by malo0140** [comment]
Did everyone fix their sizing? @isabelle6 @saracase

**Comment by isabelle6** [comment]
Yep, I took all the font size stuff out of my scss

**Comment by marisabivi** [comment]
@saracase has no extra font-sizes attached to her headers. Just needs to remove h1s from the _adopt _ page so there is only one. Other headings that need to be the same size as h1 can be styled with .exa as a class.

**Comment by shelbyboyd** [comment]
no. each page needs an h1. no other header should be the same size as h1, and every single page should have one h1. first day, first semester, first year, Thomas drilled that into our heads..

**Comment by marisabivi** [comment]
Thats what I'm saying! There are 4 h1s on the adopt page. I don't see a problem with 3 of them being made into h2s and being given the .exa class that was built into the typography page. If it shouldn't be done it wouldn't have been included.

**Comment by shelbyboyd** [comment]
Just use h2. Don't give .exa class. It would throw off consistency and nothing should be the same size as h1

**Comment by ghost** [comment]
Just changed all the h1s to h2s
