### ISSUE TITLE
Fixed scroll

### ISSUE THREAD

**Issue by marisabivi** [marisabivi/g-conservancy#45]
The content in the fixed scroll can't be scrolled through. 

@shelbyboyd 

<img width="1219" alt="screen shot 2016-03-04 at 9 35 15 pm" src="https://cloud.githubusercontent.com/assets/6371052/13545174/2f1b6a80-e251-11e5-9976-469d61e48d9a.png">
<img width="1439" alt="screen shot 2016-03-04 at 9 35 29 pm" src="https://cloud.githubusercontent.com/assets/6371052/13545175/2f285a92-e251-11e5-83b7-b27350ed77cb.png">

**Comment by shelbyboyd** [comment]
its been fixed, just not synced because im still working on the page
