### ISSUE TITLE
About headlines

### ISSUE THREAD

**Issue by marisabivi** [marisabivi/g-conservancy#53]
Left aligned on this page while all the other headlines on other pages are centered.

**Comment by malo0140** [comment]
I don't understand what your asking.

**Comment by shelbyboyd** [comment]
yes, my teal h4's are left aligned to differentiate that they are within the h3 content. I feel they are justified. It is consistent between my three pages that are the text heavy information pages.

**Comment by marisabivi** [comment]
No it wasnt the h4s just once upon a time one of your pages had all of the headings aligned to the left but its all good now!
