### ISSUE TITLE
Footer Layout

### ISSUE THREAD

**Issue by marisabivi** [marisabivi/g-conservancy#6]
The footer doesn't match the prototype for web. Please look it over again.

HTML Validation Errors
<img width="655" alt="screen shot 2016-02-23 at 5 33 30 pm" src="https://cloud.githubusercontent.com/assets/6371052/13269063/df17f4c2-da53-11e5-9f01-27ac21e84126.png">

@shelbyboyd

**Comment by shelbyboyd** [comment]
donate should be in a button so it is more prominent for the user. We also decided we wanted the graph to show people where their donations are going, so I had to move a the copyright and social media icons to right align to accomodate

**Comment by shelbyboyd** [comment]
Ah, understand better now. Fixed!
