### ISSUE TITLE
Footer Change

### ISSUE THREAD

**Issue by marisabivi** [marisabivi/g-conservancy#60]
To deal with the fixed nav over the footer I was thinking we could move in the bit about how the donations help? And for medium change it to look like it does on mobile. Everything pushed to the right? 
(if we have the time)

<img width="1299" alt="screen shot 2016-03-08 at 1 10 12 am" src="https://cloud.githubusercontent.com/assets/6371052/13593589/9484af3c-e4ca-11e5-93e4-8463b7175759.png">

**Comment by shelbyboyd** [comment]
i dont understand what your saying

**Comment by marisabivi** [comment]
Move the pie chart right! So that the fixed nav won't cover it. It's such a pretty chart I don't want it to not be seen....

**Comment by shelbyboyd** [comment]
Moving it would ruin the design; bad idea. Gave footer z-index so it sits above the nav
