### ISSUE TITLE
Someone broke the entire site

### ISSUE THREAD

**Issue by shelbyboyd** [marisabivi/g-conservancy#79]
nothing links to css or javascript or anything its just all broken

**Comment by shelbyboyd** [comment]
@tiffanytse we need to be able to revert back to commit id- ee3fef154a3fc324455a5ff0e79486d1d30238d0  this merge was the last time it worked correctly, after that everything was broken. @malo0140 and I are trying to fix it, with no avail.

**Comment by tiffanytse** [comment]
http://stackoverflow.com/questions/4114095/revert-git-repo-to-a-previous-commit @shelbyboyd

**Comment by malo0140** [comment]
This has been fixed.
