### ISSUE TITLE
Footer (Web Issue)

### ISSUE THREAD

**Issue by marisabivi** [marisabivi/g-conservancy#8]
Footer has a large white space below it in web browsers.

Footer passes Css and HTML validation. Looks good in android web browsers (opera, chrome and browser.)

@shelbyboyd

**Comment by shelbyboyd** [comment]
its because the footer isn't set to the bottom of the page, just to the bottom of content. In medium and large screen there is not enough content in the site to push the footer to the bottom, so the page finishes at the end of footer but because theres nothing left to read there is a white space.
