### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by malo0140** [marisabivi/g-conservancy#89]
The shop layout needs to be changes with a 1-4 grid structure.

**Comment by ghost** [comment]
So I made the homepage 1-4, but the only page that isn't is adopt page, I tried it with 1-4 and it doesn't look as nice
![screen shot 2016-03-11 at 9 01 44 am](https://cloud.githubusercontent.com/assets/6333956/13704067/f947a8b2-e767-11e5-81e2-541be9f56611.png)

**Comment by ghost** [comment]
![screen shot 2016-03-11 at 9 02 49 am](https://cloud.githubusercontent.com/assets/6333956/13704076/0a513308-e768-11e5-89b1-018405baffcb.png)
and theres just one by itself at the bottom

**Comment by malo0140** [comment]
<img width="1359" alt="screen shot 2016-03-12 at 11 55 21 pm" src="https://cloud.githubusercontent.com/assets/6340286/13726987/f0f8c140-e8ad-11e5-9a4e-74fb291e712c.png">
This page is the one that needs the grid.

**Comment by ghost** [comment]
added grid
